### ISSUE TITLE
Suggestion: Add option to set widths/orientations globally

### ISSUE THREAD

**Issue by mansn** [zinserjan/wdio-visual-regression-service#10]
It would be nice to be able to set the widths globally using the config file, similar to `webdrivercss`.

**Comment by zinserjan** [comment]
That makes sense. Let's do this also for orientations.

**Comment by zinserjan** [comment]
Released as [0.4.0](https://github.com/zinserjan/wdio-visual-regression-service/releases/tag/v0.4.0) (#13).
