### ISSUE TITLE
Dual screenshots

### ISSUE THREAD

**Issue by monolithed** [zinserjan/wdio-visual-regression-service#19]
![t3008_all-1050x656-os x-chrome](https://cloud.githubusercontent.com/assets/803674/19161833/12ee16e4-8bfe-11e6-9e88-a76868f054c7.png)

I see these screenshots sometimes.... it's `screenshotName` and `referenceName`

**Comment by zinserjan** [comment]
Sorry for the delay.

Sometimes? Sounds weird.

What's the real height of the page? Does it match with the screenshot height? Or is it some kind of FOUC where the page isn't fully loaded before taking screenshots?

**Comment by monolithed** [comment]
> Sometimes?

Actually, I haven't seen the problem for a log time :) 

> Does it match with the screenshot height?

Nope

> What's the real height of the page?

I did't use width/height params with `browser.checkDocument`, so I don't know

> Or is it some kind of FOUC where the page isn't fully loaded before taking screenshots?

Nope

I think we can close this issue and reopen when I'll reproduce it again

**Comment by zinserjan** [comment]
> I think we can close this issue and reopen when I'll reproduce it again

Ok
