### ISSUE TITLE
checkDocument does not respect the viewport size

### ISSUE THREAD

**Issue by monolithed** [zinserjan/wdio-visual-regression-service#20]
![img-2016-10-12-19-56-13](https://cloud.githubusercontent.com/assets/803674/19319551/fecc7482-90b5-11e6-82d3-f93a20d99e48.png)

![img-2016-10-12-19-58-19](https://cloud.githubusercontent.com/assets/803674/19319635/64e2cd52-90b6-11e6-9114-eb1b3690ea1f.png)
![img-2016-10-12-19-58-40](https://cloud.githubusercontent.com/assets/803674/19319636/64eed2dc-90b6-11e6-92d6-096be5ad2df1.png)

I expect to see the same image sizes, but `browser.checkDocument` does not agree with me :)

**Comment by zinserjan** [comment]
Yep, my team mates noticed this issue also for chrome. I think that this happen due to Ì used `windowHandleSize` instead of `setViewportSize`.

**Comment by zinserjan** [comment]
Thanks to @PM8668 for this fix.

Released with [v0.5.0](https://github.com/zinserjan/wdio-visual-regression-service/releases/tag/v0.5.0).

@monolithed let me know if this solves your issues.
