### ISSUE TITLE
Get {state: 'pending'} instead of results after check methods

### ISSUE THREAD

**Issue by avkrash** [zinserjan/wdio-visual-regression-service#22]
Hi !
I've started to receive {state: 'pending'}  as returned value for any check method. I didn't change tests or wdio_configs so far, the problem is actual for selenium grid and standalone server. The only thing that I've made is delete & re-install node_modules.

Screenshots are taken and compared with diffs in case of errors, but without returned results I can't pass/fail tests.

What could be problem with ?

**Comment by zinserjan** [comment]
No idea, when the only thing you changed is a reinstall of node_modules. 

Are you using the sync mode of wdio?

**Comment by avkrash** [comment]
Thanks for fast answer.
Yes, I'm using sync mode.

The problem was in cross-spawn-async package, I reinstall it manually (cross-spawn-async@2.2.4 installed)  and everything works fine again.

Here is the error that I've missed while re-install node_modules:

`npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!`
