### ISSUE TITLE
Allow viewport height configuration

### ISSUE THREAD

**Issue by albertogasparin** [zinserjan/wdio-visual-regression-service#31]
You have recently implemented `widths` and `orientations` configs but you left `height` out, hardcoding it at `1000`. 
Could we have it configurable? Maybe by tweaking the format, allowing an object with both width and height key?
``` js 
// ...
widths: [{ width: 360 , height: 550 }, { width: 1400 , height: 800 }],
// ...
```
(maybe calling it `sizes` might be more appropriate)

**Comment by zinserjan** [comment]
Yep, that's really an issue. We discussed about this already in #18. The idea was to replace `widths`  in favor of `dimensions` with the same format as you suggested.
