### ISSUE TITLE
Reference image updated after each run causes git change

### ISSUE THREAD

**Issue by albertogasparin** [zinserjan/wdio-visual-regression-service#32]
Every time I run my test suite, git sees my reference images as being changed even if there were no errors. Looks like [this line](https://github.com/zinserjan/wdio-visual-regression-service/blob/master/src/methods/LocalCompare.js#L47) is causing the issue:

``` js 
await fs.outputFile(referencePath, base64Screenshot, 'base64');
```

You are rewriting the reference file even if the test is passing. May I ask you why? 
Should reference images be fixed unless you explicitly delete and regenerate them?

Because something (the antialiasing?) is making invisible changes and git flags the new image as  different even with a 1 byte off.

**Comment by zinserjan** [comment]
A really good question. I have no idea why I did this, there is no real reason for this. I just thought if the changes are in tolerance it's ok to update the reference images. Never thought about a scenario that store images in git. 

I'll discuss this with my colleagues tomorrow. Maybe they have a reason for this :)

**Comment by zinserjan** [comment]
Sorry for the delay, forgot to answer...

There is really no reason to override the base screenshots. It's just a mistake in the implementation, don't know what I thought :laughing:

I would be happy to accept a PR for this, if you want to speed up this fix.
