### ISSUE TITLE
Question: ignore antialiasing

### ISSUE THREAD

**Issue by aboutandre** [zinserjan/wdio-visual-regression-service#45]
First, let me thank you for the effort you put into this!
Your work make my work much easier and even fun! =)

So, as I understand node-resemble-js is being used to do the comparison. I looked at the docs from them and I am trying to figure out how I can turn `ignore antialiasing` on.

This is how the `visualRegression` part of my `wdio.conf.js` file:

```javascript 
 visualRegression: {
    compare: new VisualRegressionCompare.LocalCompare({
      referenceName: constructScreenshotFileName(path.join(process.cwd(), 'test/screenshots/reference')),
      screenshotName: constructScreenshotFileName(path.join(process.cwd(), 'test-screenshots/screenshots/screen')),
      diffName: constructScreenshotFileName(path.join(process.cwd(), 'test-screenshots/screenshots/diff')),
      misMatchTolerance: 0.05,
      compareImages: 'antialiasing'
    }),
    viewportChangePause: 200,
    widths: [320, 544, 768, 992, 1200],
    orientations: ['landscape', 'portrait'],
  }
```

The `compareImages: 'antialiasing'` seems to be doing nothing. Is it possible to pass this parameter to node-resemble-js ?

Thanks for your help!

**Comment by zinserjan** [comment]
> First, let me thank you for the effort you put into this!
Your work make my work much easier and even fun! =)

Awesome. Thanks for the feedback. I'm happy to hear that it helps you :)

>The compareImages: 'antialiasing' seems to be doing nothing. Is it possible to pass this parameter to node-resemble-js ?

Yeah, lol seems that I already[ prepared the comparison](https://github.com/zinserjan/wdio-visual-regression-service/blob/0ac2e595fb3302a3ddd2b9602039322553d8b1ea/src/methods/LocalCompare.js#L65) for this, but forgot to make it configurable...

Just looked over their docs & code and it seems that we can just use a single option of these at a time. So we can intruduce another option like the `misMatchTolerance` that is globally configurable and also overridable per command.

But we need a name for that... no idea at the moment.

**Comment by aboutandre** [comment]
@zinserjan thanks for the quick reply!

Well the guys from @huddle call it "[comparison method](https://github.com/Huddle/Resemble.js/blob/master/README.md)". =)

**Comment by mansn** [comment]
Using "ignore antialiasing" seems to be a bit risky... Check this issue: https://github.com/Huddle/PhantomCSS/issues/67

I'm having an issue where tests fail due to antialiasing, because I'm running the tests on browserstack (i.e. many different machines)..

I was considering to use my fork of this repo, and just hard code "ignore antialiasing" for now (due to time constraints).. But I'm a bit afraid of activating it due to the issue above. I don't want to risk to get passing tests while they're actually failing (i.e. false negatives, because it didn't find a mismatch)

**Comment by SaintMitya** [comment]
A lifesaver for us =)
How about `ignoreImageDetails` for the parameter name?
