### ISSUE TITLE
There are some read requests waiting on finished stream when specifying widths

### ISSUE THREAD

**Issue by L0wry** [zinserjan/wdio-visual-regression-service#48]
Hey @zinserjan 
seem to be having difficulty when giving different viewports.
I've tried specifying viewports (0.8.0) and widths in (0.7.0) in wdio.config as well as in the test directly both of which results in
`There are some read requests waiting on finished stream`

😢 

--- wdio.config ---

    visualRegression: {
      compare: new VisualRegressionCompare.LocalCompare({
          referenceName: getScreenshotName.bind(null, 'screenshots/baseline'),
          screenshotName: getScreenshotName.bind(null, 'screenshots/latest'),
          diffName: getScreenshotName.bind(null, 'screenshots/diff')
      }),
      viewportChangePause: 10000
    },

---something.test ---

    var header = require('../../pages/header.page.js');

    describe('a visual test', function () {
            const width = {
                widths: [320, 1000]
            };

            function assertDiff(results) {
                results.forEach((result) => assert.ok(result.isExactSameImage));
            }

            before('navigate to homepage', function () {
                browser.url('/?google_nofetch');
                browser.windowHandleMaximize();
            });

            it.only('should not see any visual change to header', async function () {

                var result = browser.checkElement('.anelement', width);
                assertDiff(results);
            });
            

any ideas? Would really appreciate some help
Cheers

**Comment by zinserjan** [comment]
Did you solve this issue?

**Comment by JustFly12** [comment]
@L0wry any news? :)

**Comment by toien44** [comment]
I'm getting the same issue when running different viewports in wdio.config `    viewports: [{ width: 375, height: 667 }, { width: 768, height: 1024 }, { width: 1280, height: 837 }],` but works fine with 1 viewport (desktop)

**Comment by MartijnThiele** [comment]
Same problem for me, suite of automated tests with visualregression suddenly started failing, throwing this error
