### ISSUE TITLE
Widths option doesn't work

### ISSUE THREAD

**Issue by goldquest** [zinserjan/wdio-visual-regression-service#50]
We want to use the `widths` option of the module as documented here: http://webdriver.io/guide/services/visual-regression.html#options.
Sadly, it doesn't do anything. Even when specifying the widths on the checking commands.

**Comment by KenzoM** [comment]
@goldquest I had the same issue and got it solved here:

https://github.com/webdriverio/webdriverio/issues/2241

**Comment by goldquest** [comment]
Thanks a lot. The documentation on webdriver.io is updated and will be deployed soon. See: https://github.com/webdriverio/webdriverio/pull/2244#issuecomment-324147476
