### ISSUE TITLE
Strange artifacts in diff images

### ISSUE THREAD

**Issue by chrisfinch** [zinserjan/wdio-visual-regression-service#59]
Hi, firstly thanks for the great software.

Looking for some help regarding failing visual regression tests.

I'm getting failing tests where the generated diff has strange artifacts in and it's leaving me totally stumped.

Wondering if anyone here has seen diffs with similar artifacts and knows what the cause might be?

<img width="364" alt="screen shot 2018-01-05 at 15 59 35" src="https://user-images.githubusercontent.com/1170410/34616963-bd6229f4-f231-11e7-9a98-9b3bc00e9459.png">

Can't show the whole diff image I'm afraid as it's proprietary content for my company but the above gives a good indication and the entire diff image has the same artifacting.

Any ideas?

**Comment by avkrash** [comment]
Hi.
I've retrieved such diff images when current and reference images have different resolution.

**Comment by texttechne** [comment]
maybe the browser is still rendering...

**Comment by chrisfinch** [comment]
@avkrash thanks for the lead - maybe that's the cause...

**Comment by chrisfinch** [comment]
Turned out to be taking a shot during rendering, some pauses sorted it out.
