### ISSUE TITLE
webdriverio installed globally.

### ISSUE THREAD

**Issue by betovidal** [zinserjan/wdio-visual-regression-service#63]
Excuse me if this is a silly question, but on Windows 10, I installed webdriverio globally (npm -g install webdriverio) so I can run it >wdio from the console anywhere, but when I installed "wdio-visual-regression-service" it says there's an unmet dependency (it needs webdriverio but none was found). Do I have to keep two webdriverio installations in order for this service to work (one local and one global). Is there any way to just keep de global webdriverio and let wdio-visual-regression-service know it exists?

**Comment by tnypxl** [comment]
@betovidal _re: Do I have to keep two webdriverio installations_ &mdash; Yes, unfortunately. I'd recommend only installing packages in your specific project's root folder or installing everything globally, but never a mix of both. I know global installs are quick and convenient. But its not recommended.

**Comment by betovidal** [comment]
Thanks for the recommendation @tnypxl, I'll keep this in mind. I can see the disadvantages of maintaining global installations.

As this issue was merely informational I'll close it.
