### ISSUE TITLE
Why does travis require graphicsmagick?

### ISSUE THREAD

**Issue by meleyal** [zinserjan/wdio-visual-regression-service#7]
If [`node-resemble-js`](https://github.com/lksv/node-resemble.js) is used for image comparision why does [travis.yml](https://github.com/zinserjan/wdio-visual-regression-service/blob/master/.travis.yml#L7-L8)  require graphicsmagick? 

Just curious.

**Comment by zinserjan** [comment]
Graphicsmagick is a dependency of wdio-screenshot, which is used for capturing screenshots.

But there is a [PR](zinserjan/wdio-screenshot#10) for replacing graphicsmagick with jimp (image processing library written in JS).

**Comment by meleyal** [comment]
I see, thanks!
