### ISSUE TITLE
diff folder is not creating

### ISSUE THREAD

**Issue by vitalics** [zinserjan/wdio-visual-regression-service#80]
environment:

| name                           	|                   verion                   	|
|--------------------------------	|:------------------------------------------:	|
| OS                             	| Windows 10, version 1703, build 15063.1029 	|
| nodejs                         	| 8.9.4                                      	|
| npm                            	| 5.6.0                                      	|
|yarn | 1.2.1 |
| webdriverio                    	| 4.12.0                                     	|
| wdio-visual-regression-service 	| 0.9.0                                      	|

visual-regression service settings :
```js 
require('babel-register');

const path = require('path');
const VisualRegressionCompare = require('wdio-visual-regression-service/compare');

function getScreenshotName(basePath) {
  return function(context) {
    console.dir(context);
    const type = context.type;
    const testName = context.step.name; // cucumber step name
    const browserVersion = parseInt(context.browser.version, 10);
    const browserName = context.browser.name;
    const browserWidth = context.meta.width || context.meta.viewport.width;
    return path.join(basePath, `${testName}_${type}_${browserName}_v${browserVersion}_${browserWidth}.png`);
  };
}
exports.config = {
// settings
 visualRegression: {
    compare: new VisualRegressionCompare.LocalCompare({
      referenceName: getScreenshotName(path.join(process.cwd(), 'screenshots/reference')),
      screenshotName: getScreenshotName(path.join(process.cwd(), 'screenshots/screen')),
      diffName: getScreenshotName(path.join(process.cwd(), 'screenshots/diff')),
      misMatchTolerance: 0.01,
    }),
  },
}
```
project structure before (no screenshot folder):
![image](https://user-images.githubusercontent.com/8816260/39530791-5ffe3c96-4e32-11e8-8561-7f97ae641395.png)

screenshot folder structure after test execution:

![image](https://user-images.githubusercontent.com/8816260/39530937-b9859bb0-4e32-11e8-8ea9-2a9ac23871d1.png)

**Comment by zinserjan** [comment]
The folder isn't created when there are no diffs ;)
