### ISSUE TITLE
Demo example

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [zinserjan/wdio-visual-regression-service#9]
Do y'all have a repo or somewhere else you can point to code using the wdio-visual-regression-service in action. I'm having trouble getting started using the library and a full demo would be awesome! Thanks!

**Comment by zinserjan** [comment]
Have a look at [zinserjan/webdriverio-example](https://github.com/zinserjan/webdriverio-example).

**Comment by Blackbaud-PatrickOFriel** [comment]
That was exactly what I needed, thanks! Is there a link to that in the readme that I missed? Because if not, I can see that being handy for other folks

**Comment by zinserjan** [comment]
No, unfortunately not. But that's a good idea.

**Comment by Blackbaud-PatrickOFriel** [comment]
I can create a pull request that adds a short blurb and an link to the example repo in the readme if you'd like. Just let me know

**Comment by zinserjan** [comment]
That would be nice!
