### ISSUE TITLE
How to ignore parts of viewport

### ISSUE THREAD

**Issue by SeanHayes** [zinserjan/wdio-visual-regression-service#91]
I used `browser.checkDocument([{hide: ['img']}]);` but my diffs still show image differences. How do I ignore images? Or better yet, is there a way to force animated .gif files to always render the first frame during screenshots?

**Comment by pmerwin** [comment]
Hmm yeah hide: is not working for me either, and it looks like exclude is not implemented.

**Comment by SeanHayes** [comment]
The docs needed to be updated:
https://github.com/zinserjan/wdio-visual-regression-service/pull/92#pullrequestreview-205510429

**Comment by pmerwin** [comment]
https://github.com/zinserjan/webdriverio-example/blob/master/test/screenshot-test.js

this example helped me , needed to do hide: ['.support-chat']
